### ISSUE TITLE
🧐[问题] 求问怎么使用媒体查询 @media screen

### ISSUE THREAD

**Issue by consistent-k** [ant-design/antd-style#128]
### 🧐 问题描述

<img width="386" alt="image" src="https://github.com/ant-design/antd-style/assets/67736912/f6cdc089-7b0d-4f49-bf77-29b2877fc52d">
项目原代码有这样的代码配置。宽度是自定义的，查阅了文档 发现 responsive 不能支持这种自定义的宽度。或者是我没看明白如何用，求问这段怎么改写。

### 💻 示例代码
```css
  // 当屏幕大于等于1920时 字体设置为34px
    @media screen and (min-width: 1920px) {
        font-size: 34px;
    }

    // 当屏幕小于1279px时 不展示
    @media screen and (max-width: 1279px) {
        display: none;
    }
```
