### ISSUE TITLE
🧐[问题] 如何导出 createStyles 创建的 css 样式文本

### ISSUE THREAD

**Issue by liuweiGL** [ant-design/antd-style#189]
### 🧐 问题描述

我在使用 Lexical 富文本做模板编辑器，需要把富文本的 html 片段给后端转换成 pdf。
现在的问题是如何把 createStyles 定义的样式转换成 css 文本给后端使用。
即如何根据以下样式定义
```ts
export const useBaseStyles = createStyles(({ token }) => ({
  paragraph: {
    position: 'relative',
    margin: 0
  }
})
```
获取到对应的 css 文本

```css
.acss-x4x53h {
    position: relative;
    margin: 0;
}
```

![Image](https://github.com/user-attachments/assets/aeaa9f03-bb21-4d87-9ff2-fd31a7eba162)
